optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: true
  loss: pairwise
  log_loss: false
  test_step: 3
  reproducible: true
  seed: 2023
  patience: 5

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: amazon

model:
  name: lightgcn_gene
  # general parameters here
  keep_rate: 0.8
  embedding_size: 32
  # dataset-specific parameters here
  layer_num: 3
  reg_weight: 1.0e-7
  mask_ratio: 0.1
  recon_weight: 1.0e-1
  re_temperature: 0.2
  # for amazon
  amazon:
    layer_num: 2
    reg_weight: 1.0e-7
    mask_ratio: 0.15
    recon_weight: 0.1
    re_temperature: 0.5
  # for yelp
  yelp:
    layer_num: 2
    reg_weight: 1.0e-7
    mask_ratio: 0.05
    recon_weight: 0.01
    re_temperature: 0.1
  # for steam:
  steam:
    layer_num: 2
    reg_weight: 1.0e-6
    mask_ratio: 0.15
    recon_weight: 0.1
    re_temperature: 0.5


